# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    groups:
      actions-minor-and-patch:
        update-types: ["minor", "patch"]
      actions-majors:
        update-types: ["major"]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    groups:
      npm-minor-and-patch:
        update-types: ["minor", "patch"]
      npm-majors:
        update-types: ["major"]
    versioning-strategy: increase
    # Ignore vitest and @vitest/coverage-istanbul 4.x.x update,
    # because of peerDependencies on @cloudflare/vitest-pool-workers
    # Source: https://github.com/cloudflare/workers-sdk/blob/main/packages/vitest-pool-workers/package.json#L85
    ignore:
      - dependency-name: "vitest"
        versions: ["4.x"]
      - dependency-name: "@vitest/coverage-istanbul"
        versions: ["4.x"]
